org.gradle.jvmargs=-Xmx2G

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.3
jdk_version=25

# Mod Properties
mod_version=1.5.3
maven_group=kassuk.addon
archives_base_name=blackout

# Dependencies

# Meteor (https://maven.meteordev.org/)
meteor_version=26.2
